/**
 * Search terms real users are likely to type for common houseplants, trees,
 * and flowers - used to pre-seed the shared species cache so these don't
 * wait for organic traffic to become fast/Perenual-free. Deliberately
 * common-name-first (how people actually search), not scientific names.
 */
export const COMMON_SPECIES_QUERIES: string[] = [
  // Common houseplants
  'monstera',
  'monstera deliciosa',
  'pothos',
  'golden pothos',
  'snake plant',
  'sansevieria',
  'fiddle leaf fig',
  'peace lily',
  'spider plant',
  'zz plant',
  'philodendron',
  'philodendron brasil',
  'rubber plant',
  'rubber tree',
  'aloe vera',
  'succulent',
  'jade plant',
  'string of pearls',
  'string of hearts',
  'boston fern',
  'calathea',
  'prayer plant',
  'peperomia',
  'dracaena',
  'dracaena marginata',
  'chinese evergreen',
  'aglaonema',
  'english ivy',
  'pilea peperomioides',
  'chinese money plant',
  'anthurium',
  'bird of paradise',
  'banana plant',
  'yucca',
  'ponytail palm',
  'areca palm',
  'parlor palm',
  'bamboo palm',
  'orchid',
  'phalaenopsis orchid',
  'african violet',
  'begonia',
  'coleus',
  'croton',
  'ficus',
  'weeping fig',
  'schefflera',
  'umbrella plant',
  'cast iron plant',
  'aspidistra',
  'air plant',
  'tillandsia',
  'christmas cactus',
  'holiday cactus',
  'venus flytrap',
  'polka dot plant',
  'wandering jew',
  'tradescantia',
  'lucky bamboo',
  'money tree',
  'pachira aquatica',
  'kalanchoe',
  'hoya',
  'wax plant',
  'burros tail',
  'echeveria',
  'haworthia',
  'cactus',
  'barrel cactus',
  'elephant ear',
  'alocasia',
  'monstera adansonii',
  'swiss cheese plant',
  'creeping fig',
  'norfolk island pine',
  'asparagus fern',
  'maidenhair fern',
  'staghorn fern',

  // Common trees
  'oak tree',
  'maple tree',
  'japanese maple',
  'pine tree',
  'redwood',
  'birch tree',
  'willow tree',
  'weeping willow',
  'elm tree',
  'ash tree',
  'sycamore',
  'magnolia tree',
  'dogwood tree',
  'cherry blossom tree',
  'crepe myrtle',
  'palm tree',
  'cedar tree',
  'spruce tree',
  'fir tree',
  'cypress tree',
  'aspen tree',
  'poplar tree',
  'lemon tree',
  'orange tree',
  'lime tree',
  'apple tree',
  'peach tree',
  'fig tree',
  'olive tree',
  'avocado tree',
  'bonsai tree',
  'ficus bonsai',
  'juniper bonsai',

  // Common flowers
  'rose',
  'rose bush',
  'tulip',
  'daffodil',
  'sunflower',
  'daisy',
  'marigold',
  'petunia',
  'geranium',
  'hydrangea',
  'lavender',
  'lily',
  'peony',
  'zinnia',
  'begonia flower',
  'pansy',
  'carnation',
  'chrysanthemum',
  'dahlia',
  'iris',
  'hibiscus',
  'azalea',
  'camellia',
  'gardenia',
  'jasmine',
  'morning glory',
  'poppy',
  'snapdragon',
  'cosmos',
  'lilac',
  'hollyhock',
  'foxglove',
  'clematis',
  'bougainvillea',
  'wisteria',
  'gladiolus',
  'amaryllis',
  'begonia rex',
  'primrose',
  'aster',
];
